name: Latest blog post workflow
on:
  schedule:
    # Runs every 8 hour
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "8"
          feed_list: "https://officialrajdeepsingh.medium.com/feed, https://www.freecodecamp.org/news/author/officialrajdeepsingh/rss, https://officialrajdeepsingh.medium.com/feed"
